# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# SERVER
# ===============================
server.port=${SERVER_PORT:8080}

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=${JWT_SECRET:mySuperSecretKeyThatIsLongEnough123456}
jwt.expiration=${JWT_EXPIRATION:86400000}



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tmanager511@gmail.com
spring.mail.password=nony gcyo xvuc bxrg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=402223967860-rc9jtnkn4gfia8ahsu0mv61ihjvjp3i3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile